### ISSUE TITLE
add yaml support for data files

### ISSUE THREAD

**Issue by scasei** [Ymbra/migrate_default_content#22]
Hi,

what about YAML files, instead of CSV or along with?
I have time to implement, just wanted to know if you got some unpushed work I could use?
And, second question, where do you want the patch pushed?
Here at Github?

Regards
dan

**Comment by rodrigoaguilera** [comment]
Hello dan.

Glad to find another user of the module :)

There is plan to add json support for the data files since you can easily use rest to create the export files but please don't hesitate to add YAML. There is no code yet in any direction.

We don't really care about github or drupal.org chose what is easier for you.

**Comment by scasei** [comment]
cool, thank you
you'll see my patch here 

:)

**Comment by scasei** [comment]
hi agian, created a PR and would be glad to see your review #23
