### ISSUE TITLE
Add support for importing from JSON data files

### ISSUE THREAD

**Issue by rvilar** [Ymbra/migrate_default_content#24]
We want to add support for importing content via JSON data files and try to take advantage of REST WS.

**Comment by rvilar** [comment]
Now that we will have CSV, JSON and YAML data providers we have to think in an architecture of submodules.

Wich could be a good structure for that? Plugins maybe?

**Comment by rodrigoaguilera** [comment]
What is the use case?
So a third party can say "hey, I want to write my default content in xml,xls or whatever".

I feel once we have JSON is not worth the effort to bake a plugin manager but if someone gives a reason for using something different than CSV, YAML or JSON we can look into it.

I think we can even go as far as to deprecate the use of csv because of its plain structure nature.

So to keep this in scope I think we should implement JSON support similarly as YML is being implemented now without extensibility for new formats.

**Comment by rodrigoaguilera** [comment]
I think this requires more effort than initially was planned. Feel free to reopen on https://www.drupal.org/project/migrate_default_content/issues 
if it is still in the roadmap
